# Generated by Django 5.2.4 on 2025-07-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=222, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='адрес электронной почты')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/user_avatars', verbose_name='аватар')),
                ('role', models.CharField(choices=[('standard_user', 'Обычный пользователь'), ('manager', 'Менеджер'), ('accountant', 'Бухгалтер')], default='standard_user', max_length=20, verbose_name='Роль')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
